### ISSUE TITLE
Problem writing eleventy templates (more info in DEBUG output)

### ISSUE THREAD

**Issue by BillLudwig** [11ty/eleventy-base-blog#17]
After fresh install following instructions on Readme.

D:\StaticSites\my-blog-name>npx eleventy

Problem writing eleventy templates (more info in DEBUG output):
TypeError: Cannot read property 'inputPath' of undefined
    at TemplateMap.getUserConfigCollectionsData (D:\StaticSites\my-blog-name\node_modules\@11ty\eleventy\src\TemplateMap.js:176:16)
    at TemplateMap.cache (D:\StaticSites\my-blog-name\node_modules\@11ty\eleventy\src\TemplateMap.js:40:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by zachleat** [comment]
Hey @BillLudwig, can you attach your DEBUG output?

https://www.11ty.io/docs/debugging/

**Comment by stewwan** [comment]
hey @zachleat , facing the same here

```
Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +0ms
  Eleventy:EleventyErrorHandler Having trouble rendering template ./sitemap.xml.njk (TemplateContentRenderError) +1ms
  Eleventy:EleventyErrorHandler (log stack): TemplateContentRenderError: Having trouble rendering template ./sitemap.xml.njk
  Eleventy:EleventyErrorHandler     at Template.render (/Users/stewan/dev/stewan-io-2019/node_modules/@11ty/eleventy/src/TemplateContent.js:129:13)
  Eleventy:EleventyErrorHandler     at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
  Eleventy:EleventyErrorHandler (unknown path)
  Eleventy:EleventyErrorHandler   Error: filter not found: absoluteUrl (Template render error) +0ms
  Eleventy:EleventyErrorHandler (log stack): Template render error: (unknown path)
  Eleventy:EleventyErrorHandler   Error: filter not found: absoluteUrl
  Eleventy:EleventyErrorHandler     at Object._prettifyError (/Users/stewan/dev/stewan-io-2019/node_modules/nunjucks/src/lib.js:36:11)
  Eleventy:EleventyErrorHandler     at /Users/stewan/dev/stewan-io-2019/node_modules/nunjucks/src/environment.js:547:19
  Eleventy:EleventyErrorHandler     at Template.root [as rootRenderFunc] (eval at _compile (/Users/stewan/dev/stewan-io-2019/node_modules/nunjucks/src/environment.js:617:18), <anonymous>:60:3)
  Eleventy:EleventyErrorHandler     at Template.render (/Users/stewan/dev/stewan-io-2019/node_modules/nunjucks/src/environment.js:540:10)
  Eleventy:EleventyErrorHandler     at /Users/stewan/dev/stewan-io-2019/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:129:14
  Eleventy:EleventyErrorHandler     at new Promise (<anonymous>)
  Eleventy:EleventyErrorHandler     at /Users/stewan/dev/stewan-io-2019/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:128:14
  Eleventy:EleventyErrorHandler     at Template.render (/Users/stewan/dev/stewan-io-2019/node_modules/@11ty/eleventy/src/TemplateContent.js:121:28)
  Eleventy:EleventyErrorHandler     at process._tickCallback (internal/process/next_tick.js:68:7) +1ms
Processed 0 files in 0.57 seconds
  Eleventy Finished writing templates. +569ms
  Eleventy
  Eleventy Getting frustrated? Have a suggestion/feature request/feedback?
  Eleventy I want to hear it! Open an issue: https://github.com/11ty/eleventy/issues/new +0ms
```

**Comment by wfendler** [comment]
It looks like `package.json` includes [eleventy-plugin-rss](https://github.com/11ty/eleventy-plugin-rss) but there isn't an `.eleventy.js` config file in the project that includes it.

I got rid of this error by following the installation instructions on the RSS plugin page. That introduced a new error for `filter not found: htmlDateString` in the same sitemap file. I'm guessing that might come from [luxon](https://moment.github.io/luxon/) in some more `.eleventy.js` code that's missing?

**Comment by wfendler** [comment]
Update: I lost the `eleventy.js` file while moving things around. @stewwan and @BillLudwig perhaps you made the same mistake as me. Make sure you haven't lost the hidden dot files.

**Comment by zachleat** [comment]
Eleventy does look for `.eleventy.js` by default so make sure that you haven’t renamed it! If you want to rename, you can always use `--config=my-new-eleventy-config.js` too.

I’m going to close this one for now? Seems like y’all figured it out

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Comment by tomglynch** [comment]
> Error: filter not found: absoluteUrl

Hi @stewwan , I had the same issue as you, which I have now solved. The issue was that the example `sitemap.xlm.njk` file included references to `absoluteUrl` which is a function that comes with the RSS plugin that is installed in that site. Instead you must use something like this to create the absolute url: `<loc>https://example.com{{ item.url }}</loc>`

**Comment by mrdanielschwarz** [comment]
`No JavaScript template returned from ./test/stubs-1325/test.11ty.js (did you assign to module.exports?)` after `--serve` 🤷‍♂️
