### ISSUE TITLE
Not working to setup to "eleventyConfig.setDynamicPermalinks(false)" in .eleventy.js.

### ISSUE THREAD

**Issue by PRiMENON** [11ty/eleventy-base-blog#40]
Hi from Japan!
Thank you for making a good static site generator.

Sorry, I can't speak English, so I use Google Translate.

### system info
- Windows 10
- node.js v12.10.0
- npm v6.10.3

### steps to reproduce

 1. download eleventy-base-blog-master.zip
 1. open to PATH "C:\eleventy-base-blog-master\"
 1. run to PowerShell from C:\eleventy-base-blog-master
 1. run "npm install"
 1. edit to .eleventy.js, add to "eleventyConfig.setDynamicPermalinks(false);"
 1. run "npx eleventy"

### Actual results
<details>
<summary>message from PowerShell</summary>

```
Problem writing Eleventy templates: (more in DEBUG output)
> Output conflict: multiple input files are writing to `_site/tags/{{ tag }}/index.html`. Use distinct `permalink` values to resolve this conflict.
  1. ./tags.njk
  2. ./tags.njk
  3. ./tags.njk

`DuplicatePermalinkOutputError` was thrown:
    (Repeated output has been truncated…)
        at TemplateMap.checkForDuplicatePermalinks (C:\eleventy-base-blog-master\node_modules\@11ty\eleventy\src\TemplateMap.js:533:13)
        at TemplateMap.cache (C:\eleventy-base-blog-master\node_modules\@11ty\eleventy\src\TemplateMap.js:306:10)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async TemplateWriter._createTemplateMap (C:\eleventy-base-blog-master\node_modules\@11ty\eleventy\src\TemplateWriter.js:124:3)
        at async TemplateWriter.write (C:\eleventy-base-blog-master\node_modules\@11ty\eleventy\src\TemplateWriter.js:155:3)
        at async Eleventy.write (C:\eleventy-base-blog-master\node_modules\@11ty\eleventy\src\Eleventy.js:428:13)
Copied 2 items and Processed 0 files in 0.55 seconds (v0.9.0)
```
</details>

### Expected results
build to "_sites" directory.

Thanks.

**Comment by zachleat** [comment]
Hm? `eleventyConfig.setDynamicPermalinks(true);` is required for `eleventy-base-blog`. You can disable dynamic permalinks on a single template by using `dynamicPermalink: false` in your front matter or data file. See https://www.11ty.dev/docs/permalinks/#disable-templating-in-permalinks

Alternatively if you want to disable them globally you’ll need to delete all of the pagination templates since those won’t work when dynamic permalinks are disabled. They are:

* `eleventy-base-blog/page-list.njk`
* `eleventy-base-blog/tags.njk`

Hope that helps!

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!
