### ISSUE TITLE
Error: Filter not found: head

### ISSUE THREAD

**Issue by smolcodes** [11ty/eleventy-base-blog#58]
When I serve eleventy I keep getting the error message: Error: filter not found: head.

**Problem**
I think this is what's preventing _site from updating. I don't know though I'm very new to  SSGs and am migrating from Tumblr so am not really sure what any of this means or how to begin to fix it.

**Full Message**
```
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk template ./index.njk

`TemplateContentRenderError` was thrown
> (./index.njk)
  Error: filter not found: head

`Template render error` was thrown:
    Template render error: (./index.njk)
      Error: filter not found: head
        at Object._prettifyError (C:\Users\Me!\AppData\Roaming\npm\node_modules\@11ty\eleventy\node_modules\nunjucks\src\lib.js:36:11)
        at C:\Users\Me!\AppData\Roaming\npm\node_modules\@11ty\eleventy\node_modules\nunjucks\src\environment.js:561:19
        at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\Me!\AppData\Roaming\npm\node_modules\@11ty\eleventy\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:54:3)
        at Template.render (C:\Users\Me!\AppData\Roaming\npm\node_modules\@11ty\eleventy\node_modules\nunjucks\src\environment.js:550:10)
        at C:\Users\Me!\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\Engines\Nunjucks.js:213:14
        at new Promise (<anonymous>)
        at C:\Users\Me!\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\Engines\Nunjucks.js:212:14
        at Template.render (C:\Users\Me!\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\TemplateContent.js:182:28)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async Template._getContent (C:\Users\Me!\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\Template.js:481:12)
Copied 1 item / Wrote 0 files in 0.33 seconds (v0.10.0)
Watching…
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:8080
    External: http://192.168.56.1:8080
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------
[Browsersync] Serving files from: _site
```
**Attempt**
I tried searching for a solution on the web. In .eleventy.js I added n=1 to the collection module. I updated npm and yargs 

**Tools**
Browser:Chrome
OS: Windows 10
Eleventy v0.10.0

**Comment by ItaiAxelrad** [comment]
Make sure you have the same “head” filter in your eleventy.js file:
`
eleventyConfig.addFilter("head", (array, n) => {
    if( n < 0 ) {
      return array.slice(n);
    }   return array.slice(0, n);
  });
`
The n value should be set in the template like `{% set postslist = collections.posts | head(-3) %} `
In this case the 3

**Comment by itsjeffleong** [comment]
I got this error when I downloaded the repository from Github and moved the files and sub-folders into another folder. The files starting with a period (`.`) were hidden on my system (Mac OS X) and so files like `.eleventy.js` didn't get moved.

@smolcodes not sure if this was also your issue, but if you are still having this problem I suggest enabling hidden files on your system and following the Getting Started steps in `Readme.md` again.

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!
